### ISSUE TITLE
can't run the code

### ISSUE THREAD

**Issue by lcxsnow** [mlpc-ucsd/ViTGAN#7]
When I run "python train_stylegan2.py configs/gan/stylegan2/c10_style64.gin vitgan --mode=aug_both --aug=diffaug --lbd_r1=0.1 --no_lazy --halflife_k=1000 --penalty=bcr --use_warmup --use_nerf_proj", it appeneded the below message.

Files already downloaded and verified
Files already downloaded and verified
Traceback (most recent call last):
  File "/home/m11113013/.conda/envs/ViTGAN/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1723, in _run_ninja_build
    env=env)
  File "/home/m11113013/.conda/envs/ViTGAN/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train_stylegan2.py", line 404, in <module>
    worker(P)
  File "train_stylegan2.py", line 313, in worker
    generator, discriminator = get_architecture(P.architecture, image_size, P=P)
  File "/home/m11113013/ProjectCode/practice model/ViTGAN-main/models/gan/__init__.py", line 29, in get_architecture
    from models.gan.stylegan2.vit_generator import Generator
  File "/home/m11113013/ProjectCode/practice model/ViTGAN-main/models/gan/stylegan2/vit_generator.py", line 12, in <module>
    from models.gan.stylegan2.op import FusedLeakyReLU, conv2d_gradfix
  File "/home/m11113013/ProjectCode/practice model/ViTGAN-main/models/gan/stylegan2/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/home/m11113013/ProjectCode/practice model/ViTGAN-main/models/gan/stylegan2/op/fused_act.py", line 15, in <module>
    os.path.join(module_path, "fused_bias_act_kernel.cu"),
  File "/home/m11113013/.conda/envs/ViTGAN/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1136, in load
    keep_intermediates=keep_intermediates)
  File "/home/m11113013/.conda/envs/ViTGAN/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1347, in _jit_compile
    is_standalone=is_standalone)
  File "/home/m11113013/.conda/envs/ViTGAN/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1452, in _write_ninja_file_and_build_library
    error_prefix=f"Error building extension '{name}'")
  File "/home/m11113013/.conda/envs/ViTGAN/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1733, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'fused': [1/2] /usr/local/cuda-11.0/bin/nvcc  -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/m11113013/.conda/envs/ViTGAN/lib/python3.7/site-packages/torch/include -isystem /home/m11113013/.conda/envs/ViTGAN/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/m11113013/.conda/envs/ViTGAN/lib/python3.7/site-packages/torch/include/TH -isystem /home/m11113013/.conda/envs/ViTGAN/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda-11.0/include -isystem /home/m11113013/.conda/envs/ViTGAN/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -std=c++14 -c '/home/m11113013/ProjectCode/practice model/ViTGAN-main/models/gan/stylegan2/op/fused_bias_act_kernel.cu' -o fused_bias_act_kernel.cuda.o 
FAILED: fused_bias_act_kernel.cuda.o 
/usr/local/cuda-11.0/bin/nvcc  -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/m11113013/.conda/envs/ViTGAN/lib/python3.7/site-packages/torch/include -isystem /home/m11113013/.conda/envs/ViTGAN/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/m11113013/.conda/envs/ViTGAN/lib/python3.7/site-packages/torch/include/TH -isystem /home/m11113013/.conda/envs/ViTGAN/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda-11.0/include -isystem /home/m11113013/.conda/envs/ViTGAN/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -std=c++14 -c '/home/m11113013/ProjectCode/practice model/ViTGAN-main/models/gan/stylegan2/op/fused_bias_act_kernel.cu' -o fused_bias_act_kernel.cuda.o 
nvcc fatal   : Unsupported gpu architecture 'compute_86'
ninja: build stopped: subcommand failed.

I tried to install the older pytorch version, but it doesn't work.

**Comment by Ray006** [comment]
have you solved it? I met the same issue
